import type { SiteContent } from '@/lib/types';

export const en: SiteContent = {
  meta: {
    name: 'Victor Ramos Pasqualini',
    role: 'Data Engineer',
    location: 'São Paulo, Brazil',
    pageTitle: 'Victor Pasqualini - Senior Data Engineer',
    description:
      'Senior Data Engineer with 5+ years building large-scale pipelines on AWS and GCP — Spark, Kafka, Airflow, Databricks and lakehouse architectures.',
  },
  nav: {
    experience: 'Experience',
    projects: 'Projects',
    skills: 'Skills',
    education: 'Education',
    contact: 'Contact',
    resume: 'Resume',
  },
  hero: {
    greeting: "Hi, I'm Victor.",
    summary:
      'Data Engineer with 5+ years of experience building robust pipelines in cloud architectures. Specialized in legacy system migration, ETL/ELT processing with Spark, and data infrastructure on AWS/GCP. Focused on data quality, integrity and availability using open source technologies like Spark, Kafka and Airflow.',
  },
  sections: {
    experience: 'Experience',
    projects: 'Projects',
    skills: 'Skills',
    education: 'Education',
    certifications: 'Certifications',
    contact: 'Contact',
  },
  experience: [
    {
      period: '2025 — Present',
      role: 'Data Specialist',
      company: 'Serasa Experian',
      companyUrl: 'https://www.serasaexperian.com.br',
      viaCompany: 'ACT Digital',
      viaCompanyUrl: 'https://actdigital.com',
      description:
        'Led a complex mainframe (Cobol/DB2) to AWS pipeline migration processing massive daily positional file ingestion. Implemented data validation and quality with consolidated table generation (bronze/silver/gold) for ML and other products. Production deployment with dual-running across environments, integrations via EventBridge, REST APIs and IaC with CloudFormation.',
      stack: [
        'Spark (Scala/Python)',
        'DuckDB',
        'Pandas',
        'Polars',
        'PySpark',
        'EMR',
        'EC2',
        'Lambda',
        'SQS',
        'MSK',
        'MWAA',
        'S3',
        'Iceberg',
        'Delta Lake',
        'Athena',
        'RDS/Aurora',
        'DynamoDB',
        'DocumentDB',
        'Glue Catalog',
        'Datadog',
        'Grafana',
        'CloudWatch',
      ],
    },
    {
      period: '2025 — 2026',
      role: 'Data Engineer III',
      company: 'Vert Capital',
      companyUrl: 'https://www.vert-capital.com',
      viaCompany: 'Stech Soluções',
      viaCompanyUrl: 'https://stechsolucoes.com',
      description:
        'Maintained a Databricks ecosystem with DLT, Unity Catalog and Delta Lake ensuring 90% SLA availability. Optimized batch PySpark pipelines, reducing processing time by 40% through query optimization. Implemented a new end-to-end pipeline using PySpark, Kafka and APIs, collaborating with the Analytics team on data reliability.',
      stack: ['Databricks', 'DLT', 'Unity Catalog', 'PySpark', 'Delta Lake', 'Kafka', 'PostgreSQL', 'Django', 'Metabase', 'Power BI'],
    },
    {
      period: '2024 — 2025',
      role: 'Data Engineer II',
      company: 'Stech Soluções',
      companyUrl: 'https://stechsolucoes.com',
      description:
        'Developed an end-to-end GCP pipeline focused on data ingestion from multiple sources. Implemented data quality validations with DuckDB in Cloud Functions, and automated processes with Composer (Apache Airflow), reducing manual interventions.',
      stack: ['GCP', 'Cloud Storage', 'BigQuery', 'Compute Engine', 'Cloud Functions', 'Composer', 'Python', 'DuckDB'],
    },
    {
      period: '2022 — 2025',
      role: 'Data Engineer I',
      company: 'SPC Brasil',
      companyUrl: 'https://www.spcbrasil.com.br',
      description:
        'Data Lake architect on Hadoop/AWS (20+ TB daily) leading the on-premise to AWS migration. Delivered data quality, lead generation, credit pipelines and ML data serving. Incremental processing of XML/CSV files on-premise and on AWS, with robust orchestration across 100+ daily jobs and REST APIs.',
      stack: [
        'Spark (Scala/PySpark/Java)',
        'Hadoop',
        'Airflow',
        'Kafka',
        'NiFi',
        'Ctrl-M',
        'RabbitMQ',
        'AWS (EC2, EMR, Glue, S3, Athena)',
        'Hive',
        'Impala',
        'Sqoop',
        'Terraform',
        'MySQL',
        'MongoDB',
        'Oracle',
        'Power BI',
        'ElasticSearch',
      ],
    },
    {
      period: '2021 — 2022',
      role: 'Data Engineering Intern',
      company: 'SPC Brasil',
      companyUrl: 'https://www.spcbrasil.com.br',
      description:
        'Maintained a Data Lake on Hadoop with data cleaning and partition compaction. Developed Python/Scala scripts for integrity validation and historical reprocessing, and supported Spark infrastructure in staging and production.',
      stack: ['Hadoop', 'Python', 'Scala', 'Spark'],
    },
  ],
  education: [
    { period: '2025 – 2026', institution: 'Inbix Academy', program: 'MBA — AI for Innovation' },
    { period: '2024 – 2025', institution: 'FIAP', program: 'MBA — Data Engineering' },
    { period: '2020 – 2022', institution: 'FATEC São Paulo', program: "Bachelor's, Systems Analysis and Development" },
    { period: '2017 – 2019', institution: 'ETEC Jardim Ângela', program: 'Technical, Computer Science — Integrated High School' },
  ],
  certifications: ['MongoDB SI Associate (2025)'],
  skills: [
    { label: 'Languages', items: ['Python (PySpark, Pandas, Polars, DuckDB)', 'Scala', 'Java', 'SQL', 'Cobol'] },
    { label: 'ETL / ELT', items: ['Spark (Batch/Streaming)', 'Glue', 'EMR', 'EC2 (spot)', 'Lambda', 'Sqoop', 'Databricks', 'Compute Engine', 'Cloud Functions', 'CDC'] },
    { label: 'Messaging', items: ['Kafka', 'SQS', 'MSK', 'RabbitMQ'] },
    { label: 'Orchestration', items: ['Airflow', 'MWAA', 'EventBridge', 'Step Functions', 'Composer', 'Ctrl-M', 'NiFi', 'Databricks DLT', 'Databricks Workflows'] },
    { label: 'Storage & Lakehouse', items: ['S3', 'Glue Catalog', 'Iceberg', 'Hadoop', 'Kudu', 'BigQuery', 'Cloud Storage', 'Delta Lake', 'Unity Catalog', 'Medallion Architecture'] },
    { label: 'Databases', items: ['RDS/Aurora', 'PostgreSQL', 'MySQL', 'DynamoDB', 'MongoDB', 'DocumentDB', 'Oracle', 'DB2'] },
    { label: 'Infra', items: ['Terraform', 'Terragrunt', 'CloudFormation'] },
    { label: 'Analytics & Observability', items: ['Datadog', 'Grafana', 'Metabase', 'Power BI', 'Hive', 'Impala', 'ElasticSearch', 'CloudWatch', 'Athena'] },
    { label: 'Other', items: ['CI/CD (Cockpit)', 'Git (GitLab, Bitbucket)', 'Linux (Shell/Bash Script)'] },
  ],
  contact: {
    intro: "I'm open to new opportunities and collaborations — feel free to reach out.",
    emailLabel: 'Email',
    phoneLabel: 'Phone',
    copy: 'Copy',
    copied: 'Copied',
  },
  footer: {
    rights: 'All rights reserved.',
  },
  projects: {
    viewRepo: 'View repo',
    website: 'Website',
    fewDetails: 'Early-stage project — public details still light.',
  },
};
