import { CERTIFICATE_URLS, CREDLY_BADGE_URLS, MONGODB_CERTIFICATE_URL } from '@/lib/site';
import type { SiteContent } from '@/lib/types';

export const en: SiteContent = {
  meta: {
    name: 'Victor Ramos Pasqualini',
    shortName: 'Victor Pasqualini',
    firstName: 'Victor',
    lastName: 'Pasqualini',
    role: 'Data Engineer',
    location: 'São Paulo, Brazil',
    pageTitle: 'Victor Pasqualini - Data Specialist',
    description:
      'Senior Data Engineer with 5+ years building large-scale pipelines on AWS and GCP, with Spark, Kafka, Airflow, Databricks and lakehouse architectures.',
  },
  nav: {
    about: 'About',
    projects: 'Projects',
    skills: 'Skills',
    education: 'Education',
    contact: 'Contact',
    resume: 'Resume',
  },
  hero: {
    tagline:
      'Data Engineer building large-scale pipelines in the cloud. I migrate legacy systems, process terabytes a day with **Spark**, **Kafka**, **Airflow** and **Databricks**, and deliver consistent pipelines on **AWS** and **GCP**, with integrity and quality end to end.',
  },
  about: {
    body: [
      "I have been a Data Engineer for more than five years, designing and running pipelines in cloud architectures. I work on moving legacy systems, from on-premise **Cloudera**, **Hadoop**/**Hive** estates to **Cobol/DB2** mainframes, onto modern data platforms such as **Databricks**, with ETL/ELT processing in **Spark** and infrastructure on **AWS** and **GCP**.",
      'Across credit bureaus, capital markets and consultancies I have built medallion lakehouses over 20+ TB of daily ingestion, cut batch processing time by 40% on Databricks, and held a 90% SLA on pipelines other teams depend on. Data quality, integrity and availability are the part of the job I care about most, and open source is what I build it with.',
    ],
    stackLabel: 'Core stack',
    stack: ['Spark', 'Kafka', 'Airflow', 'Databricks', 'Iceberg', 'Delta Lake', 'Python', 'Scala', 'SQL', 'NoSQL', 'AWS', 'GCP', 'Terraform'],
    experienceLabel: 'Experience',
  },
  sections: {
    about: { label: 'About & Experience', title: 'Data Specialist.' },
    projects: { label: 'Projects', title: "What I've built" },
    skills: { label: 'Skills', title: 'The day-to-day stack' },
    education: { label: 'Education', title: 'Degrees' },
    contact: { label: 'Contact', title: 'Get in touch' },
    certifications: 'Certifications',
    badges: 'Skill Badges',
  },
  experience: [
    {
      period: '2025 — now',
      role: 'Data Specialist',
      company: 'Serasa Experian',
      companyUrl: 'https://www.serasaexperian.com.br',
      viaCompany: 'ACT Digital',
      viaCompanyUrl: 'https://actdigital.com',
      description:
        'Led a complex mainframe (Cobol/DB2) to AWS pipeline migration processing massive daily positional file ingestion. Implemented data validation and quality with consolidated table generation (bronze/silver/gold) for ML and other products. Production deployment with dual-running across environments, integrations via EventBridge, REST APIs and IaC with CloudFormation.',
      stack: [
        'Spark (Scala/Python)',
        'DuckDB',
        'Pandas',
        'Polars',
        'PySpark',
        'EMR',
        'EC2',
        'Lambda',
        'SQS',
        'MSK',
        'MWAA',
        'S3',
        'Iceberg',
        'Delta Lake',
        'Athena',
        'RDS/Aurora',
        'DynamoDB',
        'DocumentDB',
        'Glue Catalog',
        'Datadog',
        'Grafana',
        'CloudWatch',
      ],
    },
    {
      period: '2025 — 2026',
      role: 'Data Engineer III',
      company: 'Vert Capital',
      companyUrl: 'https://www.vert-capital.com',
      viaCompany: 'Stech Soluções',
      viaCompanyUrl: 'https://stechsolucoes.com',
      description:
        'Maintained a Databricks ecosystem with DLT, Unity Catalog and Delta Lake ensuring 90% SLA availability. Optimized batch PySpark pipelines, reducing processing time by 40% through query optimization. Implemented a new end-to-end pipeline using PySpark, Kafka and APIs, collaborating with the Analytics team on data reliability.',
      stack: ['Databricks', 'DLT', 'Unity Catalog', 'PySpark', 'Delta Lake', 'Kafka', 'PostgreSQL', 'Django', 'Metabase', 'Power BI'],
    },
    {
      period: '2024 — 2025',
      role: 'Data Engineer II',
      company: 'Stech Soluções',
      companyUrl: 'https://stechsolucoes.com',
      description:
        'Developed an end-to-end GCP pipeline focused on data ingestion from multiple sources. Implemented data quality validations with DuckDB in Cloud Functions, and automated processes with Composer (Apache Airflow), reducing manual interventions.',
      stack: ['GCP', 'Cloud Storage', 'BigQuery', 'Compute Engine', 'Cloud Functions', 'Composer', 'Python', 'DuckDB'],
    },
    {
      period: '2022 — 2025',
      role: 'Data Engineer I',
      company: 'SPC Brasil',
      companyUrl: 'https://www.spcbrasil.com.br',
      description:
        'Data Lake architect on Hadoop/AWS (20+ TB daily) leading the on-premise to AWS migration. Delivered data quality, lead generation, credit pipelines and ML data serving. Incremental processing of XML/CSV files on-premise and on AWS, with robust orchestration across 100+ daily jobs and REST APIs.',
      stack: [
        'Spark (Scala/PySpark/Java)',
        'Hadoop',
        'Airflow',
        'Kafka',
        'NiFi',
        'Ctrl-M',
        'RabbitMQ',
        'AWS (EC2, EMR, Glue, S3, Athena)',
        'Hive',
        'Impala',
        'Sqoop',
        'Terraform',
        'MySQL',
        'MongoDB',
        'Oracle',
        'Power BI',
        'ElasticSearch',
      ],
    },
    {
      period: '2021 — 2022',
      role: 'Data Engineering Intern',
      company: 'SPC Brasil',
      companyUrl: 'https://www.spcbrasil.com.br',
      description:
        'Maintained a Data Lake on Hadoop with data cleaning and partition compaction. Developed Python/Scala scripts for integrity validation and historical reprocessing, and supported Spark infrastructure in staging and production.',
      stack: ['Hadoop', 'Python', 'Scala', 'Spark'],
    },
  ],
  education: [
    { period: '2025 — 2026', institution: 'Inbix Academy', program: 'MBA - AI for Innovation' },
    { period: '2024 — 2025', institution: 'FIAP', program: 'MBA - Data Engineering' },
    { period: '2020 — 2022', institution: 'FATEC São Paulo', program: "Bachelor's, Systems Analysis and Development" },
    { period: '2017 — 2019', institution: 'ETEC Jardim Ângela', program: 'Technical, Computer Science (integrated high school)' },
  ],
  certifications: [
    {
      name: 'Confluent Data Streaming Engineer',
      year: '2026',
      icon: '/icons/confluent.svg',
      url: CERTIFICATE_URLS.confluentFlinkEngineer,
    },
    {
      name: 'Databricks Fundamentals',
      year: '2026',
      icon: '/icons/databricks.svg',
      url: CERTIFICATE_URLS.databricksFundamentals,
    },
    { name: 'MongoDB SI Associate', year: '2025', icon: '/icons/mongodb.svg', url: MONGODB_CERTIFICATE_URL },
  ],
  badges: [
    { name: 'MongoDB Overview', year: '2026', art: '/badges/mongodb-core-concepts.png', url: CREDLY_BADGE_URLS.mongodbOverview },
    {
      name: 'Relational to Document Model',
      year: '2026',
      art: '/badges/mongodb-document-model.png',
      url: CREDLY_BADGE_URLS.mongodbDocumentModel,
    },
    {
      name: 'Cluster Reliability',
      year: '2026',
      art: '/badges/mongodb-cluster-reliability.png',
      url: CREDLY_BADGE_URLS.mongodbClusterReliability,
    },
  ],
  skills: [
    { label: 'Languages', items: ['Python (PySpark, Pandas, Polars, DuckDB)', 'Scala', 'Java', 'SQL', 'Cobol', 'Rust'] },
    {
      label: 'ETL / ELT',
      items: [
        'Spark (Batch/Streaming)',
        'Glue',
        'EMR',
        'EC2 (spot)',
        'Lambda',
        'Sqoop',
        'DataFusion Comet',
        'Databricks',
        'Photon',
        'Snowflake',
        'Compute Engine',
        'Cloud Functions',
        'Incremental',
        'CDC',
      ],
    },
    { label: 'Messaging', items: ['Kafka', 'SQS', 'MSK', 'RabbitMQ', 'Redpanda'] },
    { label: 'Orchestration', items: ['Airflow', 'MWAA', 'EventBridge', 'Step Functions', 'Composer', 'Ctrl-M', 'NiFi', 'Databricks DLT', 'Databricks Workflows'] },
    { label: 'Storage & Lakehouse', items: ['S3', 'Glue Catalog', 'Iceberg', 'Hadoop', 'Kudu', 'BigQuery', 'Cloud Storage', 'Delta Lake', 'Unity Catalog', 'Medallion Architecture'] },
    { label: 'Databases', items: ['RDS/Aurora', 'PostgreSQL', 'MySQL', 'DynamoDB', 'MongoDB', 'DocumentDB', 'Oracle', 'DB2'] },
    { label: 'Infra', items: ['Terraform', 'Terragrunt', 'CloudFormation'] },
    { label: 'Analytics & Observability', items: ['Datadog', 'Grafana', 'Metabase', 'Power BI', 'Hive', 'Impala', 'ElasticSearch', 'CloudWatch', 'Athena'] },
    { label: 'Other', items: ['CI/CD (Cockpit)', 'Git (GitLab, Bitbucket)', 'Linux (Shell/Bash Script)'] },
  ],
  contact: {
    headline: ["Let's talk data", 'over a coffee? ☕'],
    intro:
      "A pipeline that won't close, a migration stuck halfway, a role you're hiring for, or just the urge to talk data. Reach me on whichever channel you like.",
    localTime: 'Local time',
    copy: 'Copy',
    copied: 'Copied',
  },
  footer: {
    rights: 'All rights reserved.',
  },
  projects: {
    viewRepo: 'View repo',
    website: 'Website',
    caseStudy: 'Use case',
    back: 'All projects',
    nextCase: 'Next project',
  },
  viewer: {
    expand: 'Expand',
    close: 'Close',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    reset: 'Fit to screen',
  },
};
