import {
  CERTIFICATE_URLS,
  CREDLY_BADGE_URLS,
  MONGODB_CERTIFICATE_URL,
} from '@/lib/site';
import type { SiteContent } from '@/lib/types';

export const pt: SiteContent = {
  meta: {
    name: 'Victor Ramos Pasqualini',
    shortName: 'Victor Pasqualini',
    firstName: 'Victor',
    lastName: 'Pasqualini',
    role: 'Engenheiro de Dados',
    location: 'São Paulo, Brasil',
    pageTitle: 'Victor Pasqualini - Especialista de Dados',
    description:
      'Engenheiro de Dados Senior com 5+ anos construindo pipelines de larga escala em AWS e GCP, com Spark, Kafka, Airflow, Databricks e arquiteturas lakehouse.',
  },
  nav: {
    about: 'Sobre',
    projects: 'Projetos',
    skills: 'Skills',
    education: 'Formação',
    contact: 'Contato',
    resume: 'Currículo',
  },
  hero: {
    tagline:
      'Engenheiro de Dados construindo pipelines de larga escala na nuvem. Migro sistemas legados, processo terabytes por dia com **Spark**, **Kafka**, **Airflow** e **Databricks**, e entrego pipelines consistentes na **AWS** e no **GCP**, com integridade e qualidade de ponta a ponta.',
  },
  about: {
    body: [
      'Sou Engenheiro de Dados há mais de 5 anos, desenhando e operando pipelines em arquiteturas cloud. Trabalho com migração de sistemas legados, de ambientes on-premise **Cloudera**, **Hadoop**/**Hive** a mainframes **Cobol/DB2**, para plataformas de dados modernas como **Databricks**, com processamento ETL/ELT em **Spark** e infraestrutura na **AWS** e no **GCP**.',
      'Passando por bureaus de crédito, mercado de capitais e consultorias, construí lakehouses medallion sobre 20+ TB de ingestão diária, reduzi em 40% o tempo de processamento batch no Databricks e sustentei 90% de SLA em pipelines dos quais outros times dependem. Qualidade, integridade e disponibilidade dos dados são a parte do trabalho que mais me importa, e open source é com o que construo isso.',
    ],
    stackLabel: 'Stack principal',
    stack: ['Spark', 'Kafka', 'Airflow', 'Databricks', 'Iceberg', 'Delta Lake', 'Python', 'Scala', 'SQL', 'NoSQL', 'AWS', 'GCP', 'Terraform'],
    experienceLabel: 'Experiência',
  },
  sections: {
    about: { label: 'Sobre e Experiência', title: 'Especialista de Dados.' },
    projects: { label: 'Projetos', title: 'O que eu construí' },
    skills: { label: 'Skills', title: 'A stack do dia a dia' },
    education: { label: 'Formação', title: 'Diplomas' },
    contact: { label: 'Contato', title: 'Vamos conversar' },
    certifications: 'Certificações',
    badges: 'Badges',
  },
  experience: [
    {
      period: '2025 — Hoje',
      role: 'Especialista de Dados',
      company: 'Serasa Experian',
      companyUrl: 'https://www.serasaexperian.com.br',
      viaCompany: 'ACT Digital',
      viaCompanyUrl: 'https://actdigital.com',
      description:
        'Liderou migração complexa de pipeline mainframe (Cobol/DB2) para AWS processando ingestão massiva de arquivos posicionais diários. Implementou validação e qualidade de dados com geração de tabelas consolidadas (bronze/silver/gold) para ML e outros produtos. Deploy em produção com dual-running entre ambientes, integrações via EventBridge, APIs REST e IaC com CloudFormation.',
      stack: [
        'Spark (Scala/Python)',
        'DuckDB',
        'Pandas',
        'Polars',
        'PySpark',
        'EMR',
        'EC2',
        'Lambda',
        'SQS',
        'MSK',
        'MWAA',
        'S3',
        'Iceberg',
        'DeltaLake',
        'Athena',
        'RDS/Aurora',
        'DynamoDB',
        'DocumentDB',
        'GlueCatalog',
        'Datadog',
        'Grafana',
        'CloudWatch',
      ],
    },
    {
      period: '2025 — 2026',
      role: 'Engenheiro de Dados III',
      company: 'Vert Capital',
      companyUrl: 'https://www.vert-capital.com',
      viaCompany: 'Stech Soluções',
      viaCompanyUrl: 'https://stechsolucoes.com',
      description:
        'Manteve ecossistema Databricks com DLT, Unity Catalog e Delta Lake garantindo SLA de 90% de disponibilidade. Otimizou pipelines batch PySpark, reduzindo tempo de processamento em 40% através de query optimization. Implementou novo pipeline end-to-end utilizando PySpark, Kafka e APIs, colaborando com o time de Analytics para confiabilidade de dados.',
      stack: ['Databricks', 'DLT', 'UnityCatalog', 'PySpark', 'DeltaLake', 'Kafka', 'PostgreSQL', 'Django', 'Metabase', 'PowerBI'],
    },
    {
      period: '2024 — 2025',
      role: 'Engenheiro de Dados II',
      company: 'Stech Soluções',
      companyUrl: 'https://stechsolucoes.com',
      description:
        'Desenvolveu pipeline GCP end-to-end focado em ingestão de dados de múltiplas fontes. Implementou validações de qualidade de dados com DuckDB em Cloud Functions, e automatizou processos com Composer (Apache Airflow), reduzindo intervenções manuais.',
      stack: ['GCP', 'Cloud Storage', 'BigQuery', 'Compute Engine', 'Cloud Functions', 'Composer', 'Python', 'DuckDB'],
    },
    {
      period: '2022 — 2025',
      role: 'Engenheiro de Dados I',
      company: 'SPC Brasil',
      companyUrl: 'https://www.spcbrasil.com.br',
      description:
        'Arquiteto de Data Lake em Hadoop/AWS (20+ TB diários) liderando a migração on-premise para AWS. Entregou projetos de qualidade de dados, geração de leads, pipelines de crédito e alimentação de ML. Processamento incremental de arquivos XML/CSV on-premise e em AWS, com orquestração robusta de 100+ jobs diários e APIs REST.',
      stack: [
        'Spark (Scala/PySpark/Java)',
        'Hadoop',
        'Airflow',
        'Kafka',
        'NiFi',
        'CtrlM',
        'RabbitMQ',
        'AWS (EC2, EMR, Glue, S3, Athena)',
        'Hive',
        'Impala',
        'Sqoop',
        'Terraform',
        'MySQL',
        'MongoDB',
        'Oracle',
        'PowerBI',
        'ElasticSearch',
      ],
    },
    {
      period: '2021 — 2022',
      role: 'Estagiário em Engenharia de Dados',
      company: 'SPC Brasil',
      companyUrl: 'https://www.spcbrasil.com.br',
      description:
        'Manteve Data Lake em Hadoop com limpeza de dados e compactação de partições. Desenvolveu scripts Python/Scala para validação de integridade e reprocessamento histórico, e deu suporte à infraestrutura de Spark em ambientes staging e produção.',
      stack: ['Hadoop', 'Python', 'Scala', 'Spark'],
    },
  ],
  education: [
    { period: '2025 — 2026', institution: 'Inbix Academy', program: 'MBA - IA para Inovação' },
    { period: '2024 — 2025', institution: 'FIAP', program: 'MBA - Engenharia de Dados' },
    { period: '2020 — 2022', institution: 'FATEC São Paulo', program: 'Tecnólogo, Análise e Desenvolvimento de Sistemas' },
    { period: '2017 — 2019', institution: 'ETEC Jardim Ângela', program: 'Técnico de Informática Integrado ao Médio' },
  ],
  certifications: [
    { issuer: 'Confluent', name: 'Data Streaming Engineer', year: '2026', icon: '/icons/confluent.svg', url: CERTIFICATE_URLS.confluentFlinkEngineer },
    { issuer: 'dbt Labs', name: 'dbt Fundamentals', year: '2026', icon: '/icons/dbt.svg', url: CERTIFICATE_URLS.dbtFundamentals },
    { issuer: 'Databricks', name: 'Data Governance Fundamentals', year: '2026', icon: '/icons/databricks.svg', url: CERTIFICATE_URLS.databricksDataGovernance },
    { issuer: 'Databricks', name: 'Generative AI Fundamentals', year: '2026', url: CERTIFICATE_URLS.databricksGenerativeAi },
    { issuer: 'Databricks', name: 'Databricks Fundamentals', year: '2025', url: CERTIFICATE_URLS.databricksFundamentals },
    { issuer: 'MongoDB', name: 'SI Associate', year: '2025', icon: '/icons/mongodb.svg', url: MONGODB_CERTIFICATE_URL },
  ],
  // Badge names stay in English here on purpose: the art beside them is printed in
  // English and the Credly page they open is in English, so a translated caption
  // would be the only Portuguese in sight.
  badges: [
    { name: 'MongoDB Overview', year: '2026', art: '/badges/mongodb-core-concepts.png', url: CREDLY_BADGE_URLS.mongodbOverview },
    {
      name: 'Relational to Document Model',
      year: '2026',
      art: '/badges/mongodb-document-model.png',
      url: CREDLY_BADGE_URLS.mongodbDocumentModel,
    },
    {
      name: 'Cluster Reliability',
      year: '2026',
      art: '/badges/mongodb-cluster-reliability.png',
      url: CREDLY_BADGE_URLS.mongodbClusterReliability,
    },
  ],
  skills: [
    { label: 'Linguagens', items: ['Python (PySpark, Pandas, Polars, DuckDB)', 'Scala', 'Java', 'SQL', 'Cobol', 'Rust'] },
    {
      label: 'ETL / ELT',
      items: [
        'Spark (Batch/Streaming)',
        'Flink',
        'Glue',
        'EMR',
        'EC2 (spot)',
        'Lambda',
        'Sqoop',
        'DataFusion Comet',
        'Databricks',
        'Photon',
        'Snowflake',
        'dbt',
        'Compute Engine',
        'Cloud Functions',
        'Incremental',
        'CDC',
      ],
    },
    { label: 'Mensageria', items: ['Kafka', 'SQS', 'MSK', 'RabbitMQ', 'Redpanda'] },
    { label: 'Orquestração', items: ['Airflow', 'MWAA', 'EventBridge', 'Step Functions', 'Composer', 'CtrlM', 'NiFi', 'Databricks DLT', 'Databricks Workflows'] },
    { label: 'Storage e Lakehouse', items: ['S3', 'GlueCatalog', 'Iceberg', 'Hadoop', 'Kudu', 'BigQuery', 'Cloud Storage', 'DeltaLake', 'UnityCatalog', 'Arquitetura Medalhão'] },
    { label: 'Banco de Dados', items: ['RDS/Aurora', 'PostgreSQL', 'MySQL', 'DynamoDB', 'MongoDB', 'DocumentDB', 'Oracle', 'DB2'] },
    { label: 'Infra', items: ['Terraform', 'Terragrunt', 'CloudFormation'] },
    { label: 'Analytics e Observabilidade', items: ['Datadog', 'Grafana', 'Metabase', 'PowerBI', 'Hive', 'Impala', 'ElasticSearch', 'CloudWatch', 'Athena'] },
    { label: 'Outros', items: ['CI/CD (Cockpit)', 'Git (GitLab, Bitbucket)', 'Linux (Shell/Bash Script)'] },
  ],
  contact: {
    headline: ['Bora trocar uma ideia', 'sobre dados? ☕'],
    intro:
      'Um pipeline que não fecha, uma migração parada no meio do caminho, uma vaga, ou só vontade de falar de dados. Pode me contatar por qualquer canal.',
    localTime: 'Horário local',
    copy: 'Copiar',
    copied: 'Copiado',
  },
  footer: {
    rights: 'Todos os direitos reservados.',
  },
  projects: {
    viewRepo: 'Ver repositório',
    website: 'Site',
    caseStudy: 'Caso de uso',
    back: 'Todos os projetos',
    nextCase: 'Próximo projeto',
  },
  viewer: {
    expand: 'Ampliar',
    close: 'Fechar',
    zoomIn: 'Aproximar',
    zoomOut: 'Afastar',
    reset: 'Ajustar à tela',
  },
};
